main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Classes"
    url: "/post/classes"
    weight: 2

  - name: "About"
    url: "/post/about"
    weight: 3

  - name: "Homeschool Hub"
    url: "/post/about/#homeschool-hub"
    weight: 4

buttons:
  - name: "Let's talk"
    url: "/post/about/#let-us-talk"
    weight: 5

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Classes"
    url: "/post/classes"
    weight: 2

  - name: "About"
    url: "/post/about"
    weight: 3

  # - name: "Homeschool Hub"
  #   url: "/post/about/#homeschool-hub"
  #   weight: 4
