legalName: "Moon's Delizie"
description: "We use cooking as a powerful tool to teach kids how to connect with the world around them."
images:
  - "images/academy.png"

logo: "../assets/images/logo.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  instagram: "https://www.instagram.com/moonsdelizie/"
  

location:
  - "Murrieta, California 92563"

contact:

copyright: "© 2025-present The Learning Spoon Academy, a Moon's Delizie brand. All Rights Reserved."

business:
  areaServed: "Murrieta, CA"
  priceRange: "$60-$200"
  address:
    locality: "Murrieta"
    region: "CA"
    postalCode: "92563"
    country: "US"
  hours:
    days:
      - "Tuesday"
      - "Thursday"
    opens: "10:00"
    closes: "12:00"

