title: "Moon's Delizie"
description: "We use cooking as a powerful tool to teach kids how to connect with the world around them."
images: 
  - "images/hero-image.png"

logo: "../assets/images/logo.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  instagram: "https://www.instagram.com/moonsdelizie/"
  

location:
  - "Murrieta, California 92563"

contact:
  - "amaniaseel@hotmail.com"
  - "619.807.4383"

copyright: "© 2025 MoonsDelizie All Rights Reserved"

